econ/econ/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from home.views import index

urlpatterns = [
    url(r'^$', index, name='home'),
    url(r'^regionaldata/', include('regionaldata.urls', namespace='regionaldata')),

    url(r'^admin/', include(admin.site.urls)),
]

econ/regionaldata/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^browse/([0-9]+)?', views.browse, name='browse'),
    url(r'^getdata', views.getdata, name='getdata'),
    url(r'^showdata', views.showdata, name='showdata'),
    url(r'^search/([0-9]+)?', views.search, name='search'),
    # url(r'^test/', views.test, name='test')
]

econ/regionaldata/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType



class Category(models.Model):
    name = models.CharField(max_length=200)
    parent = models.ForeignKey('self', null=True, blank=True)
    # parent = models.CharField(max_length=200)

    def __str__(self):

        if self.parent != None:
            parent = Category.objects.get(id=self.parent.id)
            return self.name + "<--" + parent.name

        else:
            return self.name


    def get_nested_list(self, depth=0):
        final = []
        cats = self.category_set.exclude(name='ROOT').order_by('id')

        if len(cats) != 0:
            for i, c in enumerate(cats):
                final.append({'id': c.id, 'name': c.name, 'depth': depth})
                final.extend(c.get_nested_list(depth+1))

        return final





class Series(models.Model):
    name = models.CharField(max_length=100)
    key = models.CharField(max_length=10)
    category = models.ForeignKey(Category, null=True)
    source = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.name





# class Code(models.Model):
#     name = models.CharField(max_length=100)
#     code = models.CharField(max_length=5)
#     type = models.CharField(max_length=50)
#
#     def __str__(self):
#         return self.name + ' - ' + self.code




class SeriesParameter(models.Model):
    series = models.ForeignKey(Series)
    key = models.CharField(max_length=100)
    value = models.CharField(max_length=250, blank=True)
    rank = models.IntegerField(default=1000)

    def __str__(self):
        return self.key + '=' + self.value + ' - ' + self.series.name





class UserOption(models.Model):
    param = models.OneToOneField(SeriesParameter)
    name = models.CharField(max_length=50)
    method = models.CharField(max_length=50)


    def __str__(self):
        return self.param.key + '=[' + self.method + '] - ' + self.param.series.name


    def get_template_name(self):
        return 'regionaldata/options/' + self.method + '.html'


    def get_series(self):
        return self.param.series

    get_series.short_description = 'Series'




class OptionParameter(models.Model):
    option = models.ForeignKey(UserOption)
    text = models.CharField(max_length=200)
    value = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.option.name + ': ' + self.text + '=' +self.value + ' - ' + self.option.param.series.name




#
# class Tag(models.Model):
#     name = models.CharField(max_length=50)
#     dataset = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.name
#
#
#
#
# class Label(models.Model):
#     value = models.CharField(max_length=200)
#     text = models.CharField(max_length=200)
#     tag = models.ForeignKey(Tag, null=True)
#
#     def __str__(self):
#         return self.text + ' - ' + self.value + ': ' + self.tag.name
#
#
#
#
# class Option(models.Model):
#     name = models.CharField(max_length=50)
#     series = models.ForeignKey(Series, null=True)
#     tag = models.ForeignKey(Tag, null=True)
#     form_type = models.CharField(max_length=50)
#
#
#     def __str__(self):
#         return self.name + ' - ' + self.series.name
#
#     def get_template_name(self):
#         return 'regionaldata/options/' + self.form_type + '.html'
#

econ/regionaldata/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.core import serializers

from regionaldata.models import Series, Category, SeriesParameter, UserOption, OptionParameter
from django.db.models import Q

import requests, re, json, urllib


def index(request):
    # Redirect to homepage
    return redirect('/')


def browse(request, series_id):

    # Prepare categories for template
    root_category = Category.objects.get(name='ROOT')
    nested_categories = root_category.get_nested_list()

    prev_depth = 2
    for cat in nested_categories:
        cat['change'] = cat['depth'] - prev_depth
        prev_depth = cat['depth']

        cat['series'] = Series.objects.filter(category=cat['id'])

    this_series = None
    user_options = []
    series_params = []

    # If id of series was provided in url, populate user options based on the series' parameters
    if series_id:
        this_series = Series.objects.get(id=series_id)
        series_params = SeriesParameter.objects.filter(series=this_series).order_by('rank')

        for param in series_params:
            param.key = param.key.replace('%', '_')
            if param.value == '' and hasattr(param, 'useroption'):
                new_option = {}

                new_option['key'] = param.key
                new_option['name'] = param.useroption.name
                new_option['method'] = param.useroption.method
                new_option['template'] = param.useroption.get_template_name()
                new_option['option_params'] = param.useroption.optionparameter_set.all()

                user_options.append(new_option)
                print(new_option)



    return render(request, 'regionaldata/browse.html', {
        'categories': nested_categories,
        'options': user_options,
        'parameters': series_params,
        'this': this_series})




def showdata(request):
    params = request.GET.dict()
    formatted_params = []

    for p in params:
        formatted_params.append({'key': p, 'value': params[p]})

    return render(request, 'regionaldata/showdata.html', {'params': formatted_params})



def search(request, series_id):

    query = request.GET.get('q', False)
    search_results = []

    if query:
        search_results = Series.objects.filter(name__icontains=query)

    this_series = None
    user_options = []
    series_params = []

    # If id of series was provided in url, populate user options based on the series' parameters
    if series_id:
        this_series = Series.objects.get(id=series_id)
        series_params = SeriesParameter.objects.filter(series=this_series).order_by('rank')

        for param in series_params:
            param.key = param.key.replace('%', '_')
            if param.value == '' and hasattr(param, 'useroption'):
                new_option = {}

                new_option['key'] = param.key
                new_option['name'] = param.useroption.name
                new_option['method'] = param.useroption.method
                new_option['template'] = param.useroption.get_template_name()
                new_option['option_params'] = param.useroption.optionparameter_set.all()

                user_options.append(new_option)


    return render(request, 'regionaldata/search.html', {
        'query': query,
        'results': search_results,
        'options': user_options,
        'parameters': series_params,
        'this': this_series})


def getdata(request):
    """ All-inclusive view that returns raw data to user - data returned depends on 'type' GET parameter """

    # TODO: more validation

    type = request.GET.get('type', False)

    if type == 'getselectdata' or type == 'getchartdata':
        """ Parameters: 'url' - url to look up data, the rest are used to populate the request
        getselectdata - Returns data to populate a 'select' option field in list of {'name': ___, 'val': ___} objects
        getchartdata - Returns data for chart """

        params = request.GET.dict()

        req_url = urllib.parse.unquote(params['url'])
        final_params = {}
        if type == 'getselectdata':
            final_params['UserID'] = '4ed778ea-6730-455d-8c60-1de273f8499d'

        for key in params:

            if key != 'type' and key != 'url':
                final_params[key] = urllib.parse.unquote(params[key])

        r = requests.get(req_url, params=final_params)
        res_json = r.json()

        final_data = []

        if type == 'getselectdata':
            for param in res_json['BEAAPI']['Results']['ParamValue']:       # Not extendable to non-BEA api services!!
                new_param = {
                    "name": param['Desc'],
                    "val": param['Key']
                }
                final_data.append(new_param)

        elif type == 'getchartdata':
            for param in res_json['BEAAPI']['Results']['Data']:
                new_param = [param['TimePeriod'], param['DataValue']]
                final_data.append(new_param)


        # Render data
        return HttpResponse(json.dumps(final_data), content_type='text/plain')


    elif type == 'getchartdata':

        params = request.GET.dict()

        req_url = urllib.parse.unquote(params['url'])
        final_params = {}

        for key in params:

            if key != 'type' and key != 'url':
                final_params[key] = urllib.parse.unquote(params[key])


    elif not type:
        return HttpResponseBadRequest('You must specify a method')


    else:
        return HttpResponseBadRequest('Method not found')

econ/regionaldata/templates/regionaldata/browse.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'regionaldata/stylesheets/global.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'regionaldata/stylesheets/browse.css' %}" />

{% include "regionaldata/header.html" with browse_active=True%}

{% if this %}
    <input type="hidden" value="{{ this.key }}" id="series_key">
{% endif %}

<div id="main" class="tabs">
    <ul id="tab-headers">

        <a href="#browse"><li class="active-tab-header">Categories</li></a>

        {% for option in options %}
            <a href="#{{ option.key }}"><li id="{{ option.key }}_tab" style="display: none;">{{ option.name }}</li></a>
        {% endfor %}

        {% if this %}
            <li id="series-name">{{ this.name }}</li>
        {% endif %}


    </ul>

    <div id="browse">
        <div class="accordion">
            {% for cat in categories %}

                {% if cat.change == -1 %}
                    </div></div></div>
                {% elif cat.change == 1 %}
                    <div class="accordion">
                {% elif cat.change == 0 %}
                    </div>
                {% endif %}

                <h3><span class="category_name">{{ cat.name }}</span></h3>
                <div>

                {% for s in cat.series %}
                    <span class="series_link"><a href="{% url 'regionaldata:browse' s.id %}" class="select-series">{{ s.name }}</a></span>
                {% endfor %}

            {% endfor %}
            </div></div></div></div>

    </div>

    {% for option in options %}
        <div id="{{ option.key }}" class="option">
            {% with option.template as template_url %}
                {% include template_url with params=option.option_params %}
            {% endwith %}

            <input type="hidden" value="{{ option.key }}" class="key">
            <input type="hidden" value="{{ option.method }}" class="method">
        </div>
    {% endfor %}

    <div id="parameters">
        {% for param in parameters %}
            <input type="hidden" class="{{ param.key }}" value="{{ param.value }}">
        {% endfor %}
    </div>


</div>

{% include 'regionaldata/footer.html' %}

<script type="text/javascript" src="{% static 'regionaldata/javascripts/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'regionaldata/javascripts/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'regionaldata/javascripts/myui.js' %}"></script>
<script type="text/javascript" src="{% static 'regionaldata/javascripts/selectseries.js' %}"></script>

econ/regionaldata/templates/regionaldata/footer.html
<div id="footer">
    Some sexy footer content here...
</div>

econ/regionaldata/templates/regionaldata/header.html
{% load staticfiles %}

<div id="header">
    <div id="header-content">
        <img src="{% static 'regionaldata/images/washington.png' %}" alt="Washington Logo" width="84" height="61" />
        <h2>Washington State Economic Research Center</h2>
    </div>

    <div id="toolbar">
        <ul>
            <li id="home-tab"><a href="/">Home</a></li>

            {% if browse_active %}
            <li id="browse-tab"><a href="/regionaldata/browse" class="active">Browse Data</a></li>
            {% else %}
            <li id="browse-tab"><a href="/regionaldata/browse">Browse Data</a></li>
            {% endif %}

            {% if search_active %}
                <li id="search-tab"><a href="/regionaldata/search" class="active">Search Data</a></li>
            {% else %}
                <li id="search-tab"><a href="/regionaldata/search">Search Data</a></li>
            {% endif %}

            <li id="more-tab"><a href="#">More eventually...</a></li>
        </ul>
    </div>
</div>

econ/regionaldata/templates/regionaldata/index.html
{% load staticfiles %}

<h1>Washington State Economic Statistics</h1>

<ul>
{% for category in category_list %}
    <li><a href="{% url 'regionaldata:select' category.KeyCode %}">{{ category.Description }}</a></li>
{% endfor %}
</ul>

<script type="text/javascript" src="{% static 'regionaldata/javascripts/jquery.min.js' %}"></script>

econ/regionaldata/templates/regionaldata/search.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'regionaldata/stylesheets/jquery-ui.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'regionaldata/stylesheets/browse.css' %}" />

{% if this %}
    <h3>{{ this.name }}</h3>
    <input type="hidden" value="{{ this.key }}" id="series_key">
{% endif %}

<div id="main" class="tabs">
    <ul id="tab_headers">
        <li><a href="#search">Search</a></li>

        {% for option in options %}
            <li id="{{ option.key }}_tab" style="display: none;"><a href="#{{ option.key }}">{{ option.name }}</a></li>
        {% endfor %}

    </ul>

    <div id="search">
        <form action="/regionaldata/search" method="get">
            {% if query %}
            <input type="search" name="q" value="{{ query }}" />
            {% else %}
            <input type="search" name="q"/>
            {% endif %}
        </form>

        <ul id="results">
        {% for result in results %}
            <a href="/regionaldata/search/{{ result.id }}/?q={{ query }}"><li>{{ result.name }}</li></a>
        {% endfor %}
        </ul>

    </div>

    {% for option in options %}
        <div id="{{ option.key }}" class="option">
            {% with option.template as template_url %}
                {% include template_url with params=option.option_params %}
            {% endwith %}

            <input type="hidden" value="{{ option.key }}" class="key">
            <input type="hidden" value="{{ option.method }}" class="method">
        </div>
    {% endfor %}

    <div id="parameters">
        {% for param in parameters %}
            <input type="hidden" class="{{ param.key }}" value="{{ param.value }}">
        {% endfor %}
    </div>

</div>

<p><a href="/regionaldata/browse/">Browse Instead</a></p>


<script type="text/javascript" src="{% static 'regionaldata/javascripts/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'regionaldata/javascripts/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'regionaldata/javascripts/selectseries.js' %}"></script>

econ/regionaldata/templates/regionaldata/showdata.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'regionaldata/stylesheets/global.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'regionaldata/stylesheets/select.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'regionaldata/stylesheets/spectrum.css' %}" />

{% include "regionaldata/header.html" with browse_active=True%}

<div id="main">

    <div id="chart"></div>

    <div id="options" class="tabs">

        <ul id="tab-headers">
            <li><a href="#notes">Notes</a></li>
            <li><a href="#graph">Graph</a></li>
            <li><a href="#share">Share</a></li>
            <li><a href="#export">Export</a></li>
            <li><a href="#cite">Cite</a></li>
        </ul>

        <div id="notes" class="active">Some brief notes on the displayed statistic.</div>
        <div id="graph">
            <div id="graph-options" class="accordion">
                <h3>Graph Settings</h3>
                <div>

                    <p>Edit global chart options</p>
                </div>
                <h3>Compare</h3>
                <div>
                    <p>Add different states and/or statistics!!!</p>
                    <select id="compare-state">
                        <option value="empty">SELECT A STATE</option>
                    </select>
                    <select id="compare-stat">
                        <option value="empty">SELECT A STATISTIC</option>
                    </select>
                    <button id="add">Add</button>
                </div>
            </div>
        </div>
        <div id="share">Let user share graph on social media, embed in a site, etc.</div>
        <div id="export">Options for exporting (as PDF, get graph data as spreadsheet, etc.)</div>
        <div id="cite">Include suggested citation here</div>

    </div>

</div>

{% include 'regionaldata/footer.html' %}


<div id="error" style="display: none;">
    <h1>Error</h1>
    <div id="message"></div>
</div>

{% for p in params %}
    <input id="{{ p.key }}" type="hidden" value="{{ p.value }}" />
{% endfor %}



<script type="text/javascript" src="{% static 'regionaldata/javascripts/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'regionaldata/javascripts/myui.js' %}"></script>
{% comment %} <script type="text/javascript" src="{% static 'regionaldata/javascripts/jquery-ui.min.js' %}"></script> {% endcomment%}
<script type="text/javascript" src="{% static 'regionaldata/javascripts/highcharts.js' %}"></script>
<script type="text/javascript" src="{% static 'regionaldata/javascripts/spectrum.js' %}"></script>
<script type="text/javascript" src="{% static 'regionaldata/javascripts/showdata.js' %}"></script>

econ/regionaldata/templates/regionaldata/test.html
{% load staticfiles %}

{{ params }}